// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:clone_shopping/utils/constants/api_constants.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: FirebaseSecret.webApiKey,
    appId: FirebaseSecret.webAppId,
    messagingSenderId:  FirebaseSecret.webMessagingSenderId,
    projectId: FirebaseSecret.webProjectId,
    authDomain: FirebaseSecret.webAuthDomain,
    databaseURL: FirebaseSecret.webDatabaseURL,
    storageBucket: FirebaseSecret.webStorageBucket,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: FirebaseSecret.androidApiKey,
    appId: FirebaseSecret.androidAppId,
    messagingSenderId: FirebaseSecret.androidMessagingSenderId,
    projectId: FirebaseSecret.androidProjectId,
    databaseURL: FirebaseSecret.androidDatabaseURL,
    storageBucket: FirebaseSecret.androidStorageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: FirebaseSecret.iosApiKey,
    appId: FirebaseSecret.iosAppId,
    messagingSenderId: FirebaseSecret.iosMessagingSenderId,
    projectId: FirebaseSecret.iosProjectId,
    databaseURL: FirebaseSecret.iosDatabaseURL,
    storageBucket: FirebaseSecret.iosStorageBucket,
    iosClientId: FirebaseSecret.iosClientId,
    iosBundleId: FirebaseSecret.iosBundleId,
  );

}